layout_spectrum: 0.9581483
typography_spectrum: 0.7161764
color:
  saturation: 0.5767713
  lightness: 0.1445695
  brandStrength: 0.4243217
  rhythmicContrast: 0.4142311
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Obstacle Ray
